# Generated by Django 4.2.7 on 2023-11-17 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TipoProducto",
            fields=[
                (
                    "nombre",
                    models.CharField(
                        db_index=True,
                        max_length=1000,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("descripcion", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "nombre",
                    models.CharField(
                        db_index=True,
                        max_length=1000,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("descripcion", models.TextField()),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="productos",
                        to="Products.tipoproducto",
                    ),
                ),
            ],
        ),
    ]
