version: '3'

services:
  web:
    image: front_mangaweb
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - mangawebnetwork
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - mangawebnetwork
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  api:
    image: api_mangaweb
    env_file:
      - ./.envs/.postgres
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - mangawebnetwork
    command: ./docker_start.sh

networks:
  mangawebnetwork:
